Repository openshift/configure-alertmanager-operator, pull requests merged in 2019-05, with the labels that each got.

#11 Override MultiNamespace (to true) in the CSV
  standard.mk
Labels: lgtm, size/XS

#13 SREP-1186: [WIP] Adopt app-sre pipeline
  Makefile
  build/Dockerfile.catalog_registry
  build/check_pr.sh
  build/deploy.sh
  build/generate-operator-bundle.py
  build/templates/csv.yaml.tmpl
  build/templates/package.yaml.tmpl
  deploy/crds/.gitkeep
  functions.mk
  project.mk
  standard.mk
Labels: size/L

#15 Break git commit newlines into their own line
  functions.mk
Labels: lgtm, size/XS

#16 SREP-1186: Add olm artifact template
  build/templates/olm-artifacts-template.yaml.tmpl
Labels: lgtm, size/M

#17 Deploy needed objects for prometheus metrics when the operator comes up
  cmd/manager/main.go
  deploy/prometheus-k8s-role.yaml
  deploy/prometheus-k8s-rolebinding.yaml
  pkg/metrics/metrics.go
  pkg/metrics/service.go
Labels: lgtm, size/L

#19 Add execute permission
  build/deploy.sh
Labels: approved, lgtm, size/XS

#21 Create OWNERS
  OWNERS
Labels: size/XS

#14 Add tests for secret controller
  Gopkg.lock
  pkg/controller/secret/secret_controller.go
  pkg/controller/secret/secret_controller_test.go
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/cmd/json-patch/file_flag.go
  vendor/github.com/evanphx/json-patch/cmd/json-patch/main.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
Labels: approved, lgtm, size/XXL

#20 Build should push images to Quay
  build/deploy.sh
Labels: approved, lgtm, size/XS

#23 Correctly identify previous CSV version
  functions.mk
Labels: approved, lgtm, size/XS

#25 Push OLM Catalog image to correct registry
  functions.mk
Labels: lgtm, size/S

#26 Fix package name
  build/templates/package.yaml.tmpl
Labels: size/XS

#27 this needs multi namespace support
  functions.mk
Labels: lgtm, size/XS

#28 Rename the function to be more clear what it does
  functions.mk
  standard.mk
Labels: approved, lgtm, size/XS

#29 SREP-1307: Remove extra newline
  build/generate-operator-bundle.py
Labels: lgtm, size/XS

#31 Revert "SREP-1307: Remove extra newline"
  build/generate-operator-bundle.py
Labels: size/XS

#32 Add metrics update function to controller
  pkg/controller/secret/secret_controller.go
Labels: approved, lgtm, size/M

#30 Added additional owners and reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#33 Added PrometheusRules for operator
  README.md
  manifests/05_prometheusrules.yaml
Labels: approved, lgtm, size/M

#36 Fix PD regex and resolved template
  pkg/controller/secret/secret_controller.go
  pkg/controller/secret/secret_controller_test.go
  pkg/types/alertmanagerconfig.go
Labels: approved, lgtm, size/XS

#35 migrate saas repo to gitlab
  functions.mk
  standard.mk
Labels: approved, lgtm, size/S

#37 Update yq image and fix select
  functions.mk
Labels: approved, lgtm, size/XS
