Repository openshift/configure-alertmanager-operator, pull requests merged in 2019-04, with the labels that each got.

#5 SREP-1143: Update Dockerfile to address build failures
  build/Dockerfile
  project.mk
Labels: size/S

#6 Updated namespace to 'openshift-monitoring'
  config/config.go
Labels: size/XS

#8 Modified the default route behavior to use DMS
  pkg/controller/secret/secret_controller.go
Labels: lgtm, size/M

#10 Instruct osd-operators-registry to not create an operatorgroup
  standard.mk
Labels: size/XS
