Repository openshift/configure-alertmanager-operator, pull requests merged in 2019-09, with the labels that each got.

#44 Add permissive option to image registry initializer
  build/Dockerfile.catalog_registry
Labels: approved, lgtm, size/XS

#42 Exclude KubeAPILatencyHigh alert
  pkg/controller/secret/secret_controller.go
  pkg/controller/secret/secret_controller_test.go
Labels: approved, lgtm, size/XS

#43 :bug: Compare version to correct thing
  functions.mk
Labels: approved, kind/bug, lgtm, size/XS

#45 Revert af011b3
  pkg/controller/secret/secret_controller.go
  pkg/controller/secret/secret_controller_test.go
Labels: approved, lgtm, size/XS

#46 Suppress KubeAPILatencyHigh
  pkg/controller/secret/secret_controller.go
  pkg/controller/secret/secret_controller_test.go
Labels: approved, lgtm, size/M
