Repository openshift/configure-alertmanager-operator, pull requests merged in 2020-03, with the labels that each got.

#66 Suppress NodeFilesystemSpaceFillingUp{severity="warning"}
  Makefile
  build/Dockerfile
  build/check_pr.sh
  functions.mk
  pkg/controller/secret/secret_controller.go
  standard.mk
Labels: approved, lgtm, size/M

#68 Mute all alerts to sre-p from openshift-customer-monitoring namespace
  pkg/controller/secret/secret_controller.go
Labels: approved, lgtm

#69 Use 'Sync' instead of 'sync' for resourceApplyMode
  build/templates/olm-artifacts-template.yaml.tmpl
Labels: approved, lgtm

#70 Update OWNERS
  OWNERS
Labels: approved, lgtm

#67 Added APAC to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#71 Suppress SLAUptimeSRE alert
  pkg/controller/secret/secret_controller.go
Labels: approved, lgtm
