Repository openshift/configure-alertmanager-operator, pull requests merged in 2020-02, with the labels that each got.

#63 Route deprecated API alerts to null
  pkg/controller/secret/secret_controller.go
  pkg/controller/secret/secret_controller_test.go
Labels: approved, lgtm, size/L

#64 Suppress CPUThrottingHigh alert where container="registry-server"
  pkg/controller/secret/secret_controller.go
  pkg/controller/secret/secret_controller_test.go
Labels: approved, lgtm, size/M

#65 Suppress alert CPUThrottlingHigh{container="configmap-registry-server"}
  pkg/controller/secret/secret_controller.go
Labels: approved, lgtm, size/XS
