Repository openshift/configure-alertmanager-operator, pull requests merged in 2025-03, with the labels that each got.

#392 SDCICD-1470: chore(deps): update konflux references
  .tekton/configure-alertmanager-operator-master-pull-request.yaml
  .tekton/configure-alertmanager-operator-master-push.yaml
  .tekton/e2e-master-pull-request.yaml
  .tekton/e2e-master-push.yaml
Labels: approved, lgtm, jira/valid-reference

#394 OSD-28521: Route etcdExcessiveDatabaseGrowth to SRE
  build/Dockerfile
  build/Dockerfile.olm-registry
  controllers/secret_controller.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#391 make bp update
  .tekton/e2e-master-pull-request.yaml
  .tekton/e2e-master-push.yaml
  OWNERS_ALIASES
  boilerplate/_data/last-boilerplate-commit
  boilerplate/openshift/golang-osd-operator-osde2e/README.md
  boilerplate/openshift/golang-osd-operator-osde2e/e2e-harness-generate.sh
  boilerplate/openshift/golang-osd-operator-osde2e/standard.mk
  boilerplate/openshift/golang-osd-operator-osde2e/update
  boilerplate/openshift/golang-osd-operator/OWNERS_ALIASES
  boilerplate/openshift/golang-osd-operator/standard.mk
  boilerplate/update
  test/e2e/Dockerfile
  test/e2e/configure_alertmanager_operator_runner_test.go
  test/e2e/configure_alertmanager_operator_tests.go
  test/e2e/test-harness-template.yml
Labels: approved, lgtm
